# Generated by Django 5.1.3 on 2024-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_identifier",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
